version: "3"
services:
  db:
    image: postgres
  redis:
    image: redis
    ports:
      - "6379:6379"
  db2:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123123123
  master:
    build: server
    environment:
      - RRRSPEC_ENV=development
      - RRRSPEC_DATABASE_HOST=db2
      - RRRSPEC_DATABASE_NAME=rrrspec_development
      - RRRSPEC_DATABASE_USERNAME=root
      - RRRSPEC_DATABASE_PASSWORD=123123123
      - REDIS_HOST=redis
    depends_on:
      - redis
      - db2
    ports:
      - "3000:3000"
  worker:
    build: worker
    environment:
      - MASTER_HOST=master
      - REDIS_HOST=redis
    depends_on:
      - redis
      - master
  client:
    build: client
    environment:
      - MASTER_HOST=master
      - REDIS_HOST=redis
    volumes:
      - .:/flowci-test
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
      - master
